### ISSUE TITLE
Cannot read property '_injectPayload' of undefined

### ISSUE THREAD

**Issue by cliqer** [chris-visser/meteor-vue-boilerplate#2]
This is happening in a clear install on the server side.
Do you happen to have any quick workaround?
```
error on fast-rendering path: / ; error: TypeError: Cannot read property '_injectPayload' of undefined
at Object.getData (packages/staringatlights:inject-data/lib/server.js:63:18)
at packages/staringatlights_fast-render.js:212:38
at packages/staringatlights_fast-render.js:288:7
error on fast-rendering path: / ; error: TypeError: Cannot read property '_injectPayload' of undefined
at Object.getData (packages/staringatlights:inject-data/lib/server.js:63:18)
at packages/staringatlights_fast-render.js:212:38
at packages/staringatlights_fast-render.js:288:7
```

**Comment by cliqer** [comment]
Never mind, yarn updated the tracker package and was throwing this error.
